    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Serializacao;
import backend.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author nunom
 */
public class AlterarPass extends javax.swing.JDialog {
private Sistema sistema;
private Serializacao bd;
    /**
     * Creates new form AlterarPass
     */
    public AlterarPass(Sistema sistema, Serializacao bd, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.sistema = sistema;
        this.bd=bd;
    }

    private void alterarPass() {
        
        if(novaPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Introduza a nova password!");
            novaPass.requestFocus();
            return;
        }
        
        if(repPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Introduza a nova password!");
            repPass.requestFocus();
            return;
        }
        
        if(passAtual.getText().equals(sistema.getUtilizadorLigado().getPassword())){
            
            if(novaPass.getText().equals(repPass.getText())){
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente alterar a password?", "Em curso...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               
                sistema.getUtilizadorLigado().setPassword(novaPass.getText());
                    
                JOptionPane.showMessageDialog(this,"Password alterada com sucesso"); 
                 System.out.println(sistema.getUtilizadorLigado().getClass().getName());
                if (!sistema.getUtilizadorLigado().getCodigoU().equals("A001") && sistema.getUtilizadorLigado().getClass().getName().equals("backend.Utilizador")){
                    HomePerfilGestor p = new HomePerfilGestor(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Medico")){
                    HomePerfilMedico p = new HomePerfilMedico(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Enfermeiro")){
                    HomePerfilEnfermeiro p = new HomePerfilEnfermeiro(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Rececionista")){
                    HomePerfilRececionista p = new HomePerfilRececionista(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.GestorHosp")){
                    HomePerfilGestorHosp p = new HomePerfilGestorHosp(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } else {
                    PerfilAdmin p = new PerfilAdmin(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } 
                }
            }
            else{
            JOptionPane.showMessageDialog(this,"Passwords diferentes!");
            novaPass.requestFocus();
            return;
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(this,"Password incorreta!");
            passAtual.requestFocus();
            return;
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        passAtual = new javax.swing.JPasswordField();
        repPass = new javax.swing.JPasswordField();
        novaPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alterar Password");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password atual");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nova Password");

        jButton5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reescrever Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jButton5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novaPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(repPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(novaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(repPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            alterarPass();    
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       //cancelar
       System.out.println(sistema.getUtilizadorLigado().getClass().getName());
       if (!sistema.getUtilizadorLigado().getCodigoU().equals("A001") && sistema.getUtilizadorLigado().getClass().getName().equals("backend.Utilizador")){
                    HomePerfilGestor p = new HomePerfilGestor(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Medico")){
                    HomePerfilMedico p = new HomePerfilMedico(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Enfermeiro")){
                    HomePerfilEnfermeiro p = new HomePerfilEnfermeiro(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.Rececionista")){
                    HomePerfilRececionista p = new HomePerfilRececionista(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }else if(sistema.getUtilizadorLigado().getClass().getName().equals("backend.GestorHosp")){
                    HomePerfilGestorHosp p = new HomePerfilGestorHosp(sistema, bd);
                    p.setVisible(true);
                    dispose();
                } else {
                    PerfilAdmin p = new PerfilAdmin(sistema, bd);
                    p.setVisible(true);
                    dispose();
                }
    }//GEN-LAST:event_jButton5ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField novaPass;
    private javax.swing.JPasswordField passAtual;
    private javax.swing.JPasswordField repPass;
    // End of variables declaration//GEN-END:variables
}
