/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;


import backend.Serializacao;
import backend.Sistema;
import backend.Utilizador;
import javax.swing.JOptionPane;

/**
 *
 * @author nunom
 */
public class EliminarUser extends javax.swing.JFrame {
private Sistema sistema;
private TabelaUtilizadores modeloTabelaUtilizadores;
private Serializacao bd;
    /**
     * Creates new form EliminarUser
     */
    public EliminarUser(Sistema sistema, Serializacao bd) {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.sistema = sistema;
        this.bd=bd;
        
        modeloTabelaUtilizadores = new TabelaUtilizadores(sistema.getListaUtilizadores());
        tabelaUtilizadores.setModel(modeloTabelaUtilizadores);
    }

    public Utilizador getUtilizadorSelecionado() {
        int row = tabelaUtilizadores.getSelectedRow();
        int column = 0;
        String value = tabelaUtilizadores.getModel().getValueAt(row, column).toString();
        
        
        if (row > -1) {
            return sistema.getListaUtilizadores().getUtilizador(value);
        }

        return null;
    }
    
    private void eliminarUser(){
    
        int column = 2;
        int row = tabelaUtilizadores.getSelectedRow();
        String value = tabelaUtilizadores.getModel().getValueAt(row, column).toString();   //vai retornar o valor que está na primeira coluna, da linha selecionada
       System.out.println(value);
        
       if(value.equals("Administrador")){
           JOptionPane.showMessageDialog(this,"Impossível remover utilizador!");
            return;
       }else {
        
        
        Utilizador selecionado = getUtilizadorSelecionado();
        if (selecionado != null) {
            sistema.getListaUtilizadores().remover(getUtilizadorSelecionado());
            JOptionPane.showMessageDialog(this,"Utilizador removido com sucesso!");
            modeloTabelaUtilizadores = new TabelaUtilizadores(sistema.getListaUtilizadores());      //vai recarregar a tabela
        tabelaUtilizadores.setModel(modeloTabelaUtilizadores);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Utilizador!");
        }
       }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUtilizadores = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar Utilizador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 310, 40));

        tabelaUtilizadores.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabelaUtilizadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUtilizadores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 380, 180));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setAlignmentY(0.0F);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminTelaPrincipal p = new AdminTelaPrincipal(sistema, bd);
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente remover o Utilizador?", "Em curso...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.out.println(JOptionPane.YES_NO_OPTION);
        eliminarUser();
        }
        else{
            dispose();
            EliminarUser a = new EliminarUser(sistema, bd);
            a.setVisible(true);
        }
           
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUtilizadores;
    // End of variables declaration//GEN-END:variables
}
